export const defaultDataset = {
  overview: {
    total_video_count: 320,
    total_exposure: 12226000,
    overall_5s_completion_rate: 0.14130565993542035,
    overall_5s_completion_rate_display: "14.1%",
    actor_video_count: 71,
    actor_count: 10,
    quality_status: "3 个 sheet 缺少 5S",
    source_file_name: "26年账号曝光统计表-星途新媒体（统计台账） .xlsx",
    generated_at: "2026-06-06T13:51:00",
  },
  account_metrics: [
    { platform: "抖音", account_name: "抖音驭见星豪华", video_count: 95, exposure: 9680285, average_exposure: 101897.74, completion_5s_display: "9.7%", completion_field_source: "5S完播率", actor_video_count: 60, missing_actor_video_count: 35 },
    { platform: "抖音", account_name: "抖音星空拍车show", video_count: 10, exposure: 1216399, average_exposure: 121639.9, completion_5s_display: "46.2%", completion_field_source: "5S完播率", actor_video_count: 2, missing_actor_video_count: 8 },
    { platform: "视频号", account_name: "视频号星际领航员", video_count: 103, exposure: 578072, average_exposure: 5612.35, completion_5s_display: "未提供", completion_field_source: "未提供", actor_video_count: 4, missing_actor_video_count: 99 },
    { platform: "视频号", account_name: "视频号全民驾值观", video_count: 49, exposure: 334746, average_exposure: 6831.55, completion_5s_display: "未提供", completion_field_source: "未提供", actor_video_count: 0, missing_actor_video_count: 49 },
    { platform: "抖音", account_name: "抖音极速拍档", video_count: 28, exposure: 276757, average_exposure: 9884.18, completion_5s_display: "16.7%", completion_field_source: "5S完播率", actor_video_count: 3, missing_actor_video_count: 25 },
    { platform: "抖音", account_name: "抖音全民驾值观", video_count: 33, exposure: 139451, average_exposure: 4225.79, completion_5s_display: "34.8%", completion_field_source: "5S完播率", actor_video_count: 0, missing_actor_video_count: 33 },
    { platform: "小红书", account_name: "小红书", video_count: 2, exposure: 290, average_exposure: 145, completion_5s_display: "31.9%", completion_field_source: "5S完播率", actor_video_count: 2, missing_actor_video_count: 0 },
    { platform: "视频号", account_name: "视频号星空拍车show", video_count: 0, exposure: 0, average_exposure: 0, completion_5s_display: "未提供", completion_field_source: "无有效视频行", actor_video_count: 0, missing_actor_video_count: 0 },
  ],
  actor_metrics: [
    { actor_name: "桂婕", video_count: 29, account_count: 3, contributed_exposure: 3751858, accounts: "抖音极速拍档、抖音驭见星豪华、视频号星际领航员" },
    { actor_name: "刘花旗", video_count: 17, account_count: 2, contributed_exposure: 1349223, accounts: "抖音极速拍档、抖音驭见星豪华" },
    { actor_name: "陶雯义", video_count: 13, account_count: 3, contributed_exposure: 1407484, accounts: "抖音星空拍车show、抖音极速拍档、抖音驭见星豪华" },
    { actor_name: "岳浩然", video_count: 10, account_count: 2, contributed_exposure: 2422589, accounts: "抖音星空拍车show、抖音驭见星豪华" },
    { actor_name: "曹嘉洋", video_count: 9, account_count: 2, contributed_exposure: 757298, accounts: "小红书、抖音驭见星豪华" },
    { actor_name: "花旗", video_count: 5, account_count: 2, contributed_exposure: 165765, accounts: "抖音驭见星豪华、视频号星际领航员" },
    { actor_name: "徐欣悦", video_count: 5, account_count: 2, contributed_exposure: 140805, accounts: "抖音驭见星豪华、视频号星际领航员" },
    { actor_name: "王雪", video_count: 3, account_count: 1, contributed_exposure: 1043, accounts: "抖音驭见星豪华" },
    { actor_name: "徐幻", video_count: 2, account_count: 2, contributed_exposure: 1210, accounts: "抖音驭见星豪华、视频号星际领航员" },
    { actor_name: "丁俐佳", video_count: 1, account_count: 1, contributed_exposure: 340, accounts: "抖音驭见星豪华" },
  ],
  video_rankings: {
    top: {
      platform: "抖音",
      account_name: "抖音驭见星豪华",
      video_title: "ASMR沉浸式座舱，星途3.0家族，舒服到小猫酣然熟睡 #性能豪华激情梦想 #全球性能豪华创新者 #2026北京车展 #EXEED星途汽车#ASMR",
      publish_time: "2026/4/25 22:57",
      exposure: 1066313,
      actors: "",
    },
    bottom: {
      platform: "抖音",
      account_name: "抖音全民驾值观",
      video_title: "特朗普访华恰逢APEC盛会，星途EX7惊艳出圈，排面拉满！这场国际盛会太有排面#特朗普访华#星途EX7#星途服务APEC#陆上专机护航APEC",
      publish_time: "2026/5/19 15:14",
      exposure: 0,
      actors: "",
    },
  },
  quality_report: {
    used_sheets: ["抖音极速拍档", "抖音驭见星豪华", "视频号星际领航员", "抖音星空拍车show", "抖音全民驾值观", "视频号星空拍车show", "视频号全民驾值观", "小红书"],
    excluded_sheets: ["总月度数据表", "涨粉计划", "月度爆款汇总表", "各账号月度数据明细", "月度爆款登记", "部门协同", "3月短引直台账", "看后搜情况"],
    missing_fields: { 视频号星际领航员: ["5S完播率"], 视频号星空拍车show: ["5S完播率"], 视频号全民驾值观: ["5S完播率"] },
    sheet_issues: { 视频号星空拍车show: ["无有效视频行"] },
    invalid_values: {},
    sheets_without_5s_completion: ["视频号全民驾值观", "视频号星空拍车show", "视频号星际领航员"],
    notes: ["视频号 5S 未提供", "演员曝光不平摊"],
  },
};

export const oaePendingDataset = {
  overview: {
    total_video_count: 219,
    total_exposure: 7514978,
    overall_5s_completion_rate: 0.30059912,
    overall_5s_completion_rate_display: "30.1%",
    actor_video_count: 22,
    actor_count: 8,
    quality_status: "已接入 OAE dashboard source",
    source_file_name: "feishu_dashboard_source_latest_2026-06-08.tsv",
    generated_at: "2026-06-08",
    module_status: "ready",
    report_date: "2026-06-08",
    source_contract: "feishu_dashboard_source_tsv",
  },
  account_metrics: [],
  actor_metrics: [],
  video_rankings: { top: null, bottom: null },
  oae_dashboard: {
    report_date: "2026-06-08",
    available_report_dates: ["2026-06-05", "2026-06-07", "2026-06-08"],
    source: { type: "feishu_dashboard_source_tsv", path: "sample", rows: 121 },
    kpis: [
      { metric_key: "impressions", metric_name: "曝光", actual: 7514978, target: 25000000, attain_rate: 0.30059912, unit: "次" },
      { metric_key: "mtd_unique_leads", metric_name: "累计唯一线索", actual: 219, target: 0, attain_rate: null, unit: "条" },
      { metric_key: "mtd_douyin_laike_orders", metric_name: "抖音-来客线索（手机号去重）", actual: 51, target: 1000, attain_rate: 0.051, unit: "条" },
      { metric_key: "mtd_deals", metric_name: "累计实销", actual: 22, target: 100, attain_rate: 0.22, unit: "台" },
    ],
    segments: [],
    lead_accounts: [],
    lead_anchors: [],
    seed_account: { account_name: "EXEED星途", daily_impressions: 1855993, mtd_impressions: 6874177, mtd_impressions_attain_rate: 0.27496708 },
    seed_anchors: [],
    quality_metrics: [],
    trends: [
      { report_date: "2026-06-05", impressions: 1602487, mtd_unique_leads: 138, mtd_douyin_laike_orders: 25, mtd_deals: 16, mtd_spend: 1525.09 },
      { report_date: "2026-06-07", impressions: 5747742, mtd_unique_leads: 191, mtd_douyin_laike_orders: 38, mtd_deals: 19, mtd_spend: 11950.14 },
      { report_date: "2026-06-08", impressions: 7514978, mtd_unique_leads: 219, mtd_douyin_laike_orders: 51, mtd_deals: 22, mtd_spend: 21361.03 },
    ],
  },
  quality_report: {
    used_sheets: [],
    excluded_sheets: [],
    missing_fields: {},
    sheet_issues: {},
    invalid_values: {},
    sheets_without_5s_completion: [],
    notes: ["OAE 数据读取自 dashboard source TSV", "原始多源清洗由 OAE pipeline 完成"],
  },
};

export const sampleDatasets = {
  xingtu: defaultDataset,
  oae: oaePendingDataset,
};
